export default [
  {
    id: 1,
    img: {
      src: "https://images.unsplash.com/photo-1635914741250-2391bd64f1ca?q=80&w=928&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Lake Bled",
    },
    title: "Lake Bled",
    country: "Slovenia",
    googleMapsLink: "https://maps.app.goo.gl/ucyL6RraoiXdnL5Y9",
    dates: "12 Jan, 2024 - 24 Jan, 2024",
    text: "Lake Bled is a lake in the Julian Alps of the Upper Carniolan region of northwestern Slovenia, where it adjoins the town of Bled.",
  },
  {
    id: 2,
    img: {
      src: "https://scrimba.com/links/travel-journal-australia-image-url",
      alt: "Sydney Opera House",
    },
    title: "Sydney Opera House",
    country: "Australia",
    googleMapsLink: "https://maps.app.goo.gl/Zr17SCrsJeCEKMd36",
    dates: "10 Mar, 2024 - 22 Mar, 2024",
    text: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings.",
  },
  {
    id: 3,
    img: {
      src: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?q=80&w=2064&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Golden Gate Bridge",
    },
    title: "Golden Gate Bridge",
    country: "USA",
    googleMapsLink: "https://maps.app.goo.gl/uotgWfPDgZUSnCwu5",
    dates: "05 Jun, 2024 - 18 Jun, 2024",
    text: "The Golden Gate Bridge is a suspension bridge spanning the Golden Gate, the one-mile-wide (1.6 km) strait connecting San Francisco Bay and the Pacific Ocean in California, United States.",
  },
  {
    id: 4,
    img: {
      src: "https://plus.unsplash.com/premium_photo-1719581957038-0121108b9455?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Eiffel Tower",
    },
    title: "Eiffel Tower",
    country: "France",
    googleMapsLink: "https://maps.app.goo.gl/1r8aAuT53rJgKxJN7",
    dates: "14 Sep, 2024 - 27 Sep, 2024",
    text: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower from 1887 to 1889.",
  },
  {
    id: 5,
    img: {
      src: "https://images.unsplash.com/photo-1578637387939-43c525550085?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Mount Fuji",
    },
    title: "Mount Fuji",
    country: "Japan",
    googleMapsLink: "https://maps.app.goo.gl/6RLYZDuuuqJ7kNGZ9",
    dates: "03 Dec, 2024 - 15 Dec, 2024",
    text: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
  },
  {
    id: 6,
    img: {
      src: "https://images.unsplash.com/photo-1511489731872-324afc650052?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fGxha2UlMjBsb3Vpc2V8ZW58MHx8MHx8fDA%3D",
      alt: "Lake Louise",
    },
    title: "Lake Louise",
    country: "Canada",
    googleMapsLink: "https://maps.app.goo.gl/3iYPUHrxqQHZezS38",
    dates: "20 Feb, 2025 - 03 Mar, 2025",
    text: "Lake Louise is a glacial lake within Banff National Park in Alberta, Canada. It is named after the Princess Louise Caroline Alberta, the fourth daughter of Queen Victoria. ",
  },
  {
    id: 7,
    img: {
      src: "https://images.unsplash.com/photo-1521651201144-634f700b36ef?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Kruger National Park",
    },
    title: "Kruger National Park",
    country: "South Africa",
    googleMapsLink: "https://maps.app.goo.gl/3u96APo4vCrK1GDx7",
    dates: "12 Apr, 2025 - 25 Apr, 2025",
    text: "Kruger National Park is a national park in South Africa covering an area of 19,623 km2 (7,576 sq mi) in the provinces of Limpopo and Mpumalanga in the country's northeast. It extends 360 km (220 mi) from north to south and 65 km (40 mi) from east to west.",
  },
  {
    id: 8,
    img: {
      src: "https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "The Matterhorn",
    },
    title: "Matterhorn",
    country: "Switzerland",
    googleMapsLink: "https://maps.app.goo.gl/r3KE3Eez3p5EqYtv8",
    dates: "05 Jun, 2025 - 17 Jun, 2025",
    text: "The Matterhorn is a mountain of the Alps, straddling the border between Switzerland and Italy. It is a large, near-symmetric pyramidal peak whose summit is 4,478 metres (14,692 ft) above sea level, making it one of the highest summits in the Alps and Europe.",
  },
];
